### ISSUE TITLE
Sunken penguin bug(Graphic).

### ISSUE THREAD

**Issue by Diego13** [fga150/FrozenWarsIS#14]
When a player is dead, if you put an harpoon that catchs the penguin respawn area, the game displays an animation of sunken penguin.

**Comment by YxNoK** [comment]
mmm is so strange, you can't put an harpoon if you are dead.

**Comment by Diego13** [comment]
I said that when player 1 dies, player 2 put an harpoon near the respawn area of player1 you can see that the graphics apears :)

**Comment by YxNoK** [comment]
jajaja ok i hadn't understood. thanks for the explanation
