### ISSUE TITLE
Initial countdown

### ISSUE THREAD

**Issue by PhoenixDCB** [fga150/FrozenWarsIS#26]
When you run the aplication, when the countdown finish, the aplication doesn't close (as I can read in the message), then the game begins.

I don't know if the message is wrong or I don't understand the message.

**Comment by fga150** [comment]
What it actually means is that that window will close and the InitialScreen window (Play, settings, help, exit) is going to appear. Anyway this has already been replaced for the app logo this afternoon.
Thanks anyway!
