### ISSUE TITLE
Not filled room

### ISSUE THREAD

**Issue by PhoenixDCB** [fga150/FrozenWarsIS#27]
When the room is not filled, you can see all players (include the players doesn't play). It would be good that this players doesn't appear or this players are bots.

**Comment by fga150** [comment]
I dont quite understand you. You mean in the screen "Friend List"? (playin1, 2, 3.. etc)
If you meant so, i just fixed it this afternoon. Now its shows your current friends (conected, disconected and playing a game).

**Comment by PhoenixDCB** [comment]
No, I mean that when we are playing 2 players in a match, we can see the four penguins, and 2 of them are not controlled by anyone.

I think that it would be good they don't appear in the match, or they are controlled by the computer.

**Comment by fga150** [comment]
Ohh sure, those penguins will be removed so you only see the penguins controlled by players. We will be working on it soon.
Thanks!
